### ISSUE TITLE
Why swiper as a dependency?

### ISSUE THREAD

**Issue by Seb33300** [kunalnagarco/action-cve#181]
I just saw the latest release about upgrading swiper.

[Swiper](https://swiperjs.com/) is a javascript library to render carousel on web pages.
I don't understand why it is required by this project and I cannot find any usage of it in the code base.

**Comment by Seb33300** [comment]
Added by @kunalnagar in https://github.com/kunalnagarco/action-cve/commit/bb547f9e96ee8949d84df280c75ae7097d9b60b8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by kunalnagar** [comment]
@Seb33300 - thanks, this is a good catch. I don't think this is needed but I'll investigate how it got added in the first place.

**Comment by kunalnagar** [comment]
@Seb33300 - I remember now - this is the reason why I had to add: https://github.com/kunalnagarco/action-cve/actions/runs/8648505040/job/23712460836?pr=182#step:8:1

Although, I should investigate what's going on with this. Let me know if you have any thoughts.
