### ISSUE TITLE
Add support for org and enterprise level alerts

### ISSUE THREAD

**Issue by mauritz-lovgren** [kunalnagarco/action-cve#187]
Currently, the action only supports the `octokit.dependabot.listAlertsForRepo(...)` function.

Would be nice to support the [organization](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#list-dependabot-alerts-for-an-organization) and [enterprise](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#list-dependabot-alerts-for-an-enterprise) editions as well.

Instead of having to define a workflow for **_all_** repos in all organizations in the whole enterprise, one could simply create one single workflow in an org-level repo (.github) to schedule a weekly report for one or more organizations (or for the whole enterprise).

**Comment by kunalnagar** [comment]
@mauritz-lovgren - this sounds like a great feature. I'll see how to plan this, thanks for the suggestion!

**Comment by mauritz-lovgren** [comment]
Great, thank you! 👍
