### ISSUE TITLE
What permissions are needed for the personal access token?

### ISSUE THREAD

**Issue by LyDawei** [kunalnagarco/action-cve#68]
What permissions are needed for the personal access token?

**Comment by m-standfuss** [comment]
This would be great to provide.

**Comment by m-standfuss** [comment]
Actually if you run it on a taken without any permissions you get this error message 

```GraphqlResponseError: Request failed due to following response errors:
 - Your token has not been granted the required scopes to execute this query. The 'id' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: [''] scopes. Please modify your token's scopes at: ```

**Comment by kunalnagar** [comment]
@LyDawei @m-standfuss:

I've tested it with the following permissions:

![image](https://user-images.githubusercontent.com/2741371/170594362-8aa628d9-0ea2-4ac2-8c08-82f0cd44e3c3.png)

If you require tighter control, you could try and uncheck one by one and see where it breaks? Thanks!
